project_name: "geo-climb"
embedding_directories:
  - "dem_rcf_empirical"
  - "lithology_scibert_no_description"
  # - "sentinel_mosaiks"

hyperparameters:
  batch_size: 32
  max_epochs: 50
  learning_rate: 0.001
