import os
import sys
import numpy as np
import rasterio
import torch
from torchgeo.models import RCF
from torchvision.transforms import ToTensor


sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from config.config import Config
from utils.file_utils import *


def preprocess_dem(dem_data):
    """
    Normalize DEM data by subtracting the minimum value to simulate sea level.

    Args:
        dem_data (numpy.ndarray): 2D array representing the DEM data.

    Returns:
        numpy.ndarray: Normalized DEM data with the minimum value set to zero.
    """
    min_value = np.min(dem_data)
    normalized_data = dem_data - min_value
    return normalized_data


def get_embedding(dem_data):
    """
    Generate embeddings for DEM data using torchgeo's RandomFeatureConvolution model.

    Args:
        dem_data (numpy.ndarray): 2D array representing the DEM data.

    Returns:
        torch.Tensor: Embeddings generated by the RCF model.
    """
    # Convert the DEM data to a PyTorch tensor
    dem_tensor = (
        torch.tensor(dem_data, dtype=torch.float32).unsqueeze(0).unsqueeze(0)
    )  # Shape: (1, 1, H, W)

    # print(dem_tensor.shape)

    # Initialize the RCF model
    model = RCF(in_channels=1, features=256, kernel_size=2)
    model.eval()

    with torch.no_grad():
        embeddings = model(dem_tensor)

    # Flatten the embeddings to a 1D vector
    return embeddings.flatten()


if __name__ == "__main__":
    directory = Config.DATA_DIR_UNLBL_DEM
    embeddings_dir = "data/unlabeled/embeddings/dem"
    # directory = Config.DATA_DIR_UNLBL_LITH
    print(directory)

    for dem_file in os.listdir(directory):
        dem_full_path = os.path.join(directory, dem_file)
        os.makedirs(embeddings_dir, exist_ok=True)
        if dem_file.endswith(".tif"):
            lat, lon = decode_file(dem_file)

            with rasterio.open(dem_full_path) as src:
                dem_data = src.read(1)

            # Normalize the DEM data to sea level
            dem_data = preprocess_dem(dem_data)

            embedding = get_embedding(dem_data)
            np.save(
                encode_file(lat, lon, "dem", embeddings_dir, "npy"), embedding.numpy()
            )
