import os
from dotenv import load_dotenv

load_dotenv()

DATA_DIR_LBL_SEN = os.getenv("DATA_DIR_LBL_SEN")
DATA_DIR_LBL_DEM = os.getenv("DATA_DIR_LBL_DEM")
DATA_DIR_LBL_LITH = os.getenv("DATA_DIR_LBL_LITH")
DATA_DIR_UNLBL_SEN_EMBEDS=os.getenv("DATA_DIR_UNLBL_SEN_EMBEDS")
DATA_DIR_LBL_SEN_EMBEDS=os.getenv("DATA_DIR_LBL_SEN_EMBEDS")
DATA_DIR_UNLBL_SEN = os.getenv("DATA_DIR_UNLBL_SEN")
DATA_DIR_UNLBL_DEM = os.getenv("DATA_DIR_UNLBL_DEM")
DATA_DIR_UNLBL_LITH = os.getenv("DATA_DIR_UNLBL_LITH")

DATA_DIR_LBL_LITH_EMB = os.getenv("DATA_DIR_LBL_LITH_EMB")
DATA_DIR_UNLBL_LITH_EMB = os.getenv("DATA_DIR_UNLBL_LITH_EMB")


class Config:
    DATA_DIR_LBL_SEN = DATA_DIR_LBL_SEN
    DATA_DIR_LBL_DEM = DATA_DIR_LBL_DEM
    DATA_DIR_LBL_LITH = DATA_DIR_LBL_LITH
    DATA_DIR_UNLBL_SEN_EMBEDS=DATA_DIR_UNLBL_SEN_EMBEDS
    DATA_DIR_LBL_SEN_EMBEDS=DATA_DIR_LBL_SEN_EMBEDS
    DATA_DIR_UNLBL_SEN = DATA_DIR_UNLBL_SEN
    DATA_DIR_UNLBL_DEM = DATA_DIR_UNLBL_DEM
    DATA_DIR_UNLBL_LITH = DATA_DIR_UNLBL_LITH

    DATA_DIR_LBL_LITH_EMB = DATA_DIR_LBL_LITH_EMB
    DATA_DIR_UNLBL_LITH_EMB = DATA_DIR_UNLBL_LITH_EMB
